#!/usr/bin/python
import os, sys

default_ip = ['192.168.3.', '192.168.', '192.']

def ssh_connect(user, host, password):
    cmd = "sshpass -p " + password + " ssh -X -o StrictHostKeyChecking=no " + user + "@" + host
    os.system(cmd)
    pass

def ssh_combine(user, part_ip, password):
    num = part_ip.count('.')
    if num < 3:
        return ssh_connect(user, default_ip[num] + part_ip, password)
    else:
        return ssh_connect(user, part_ip, password)

def Main():
    if len(sys.argv) == 2:
        return ssh_combine('root', sys.argv[1], 'defaultpass')
    if len(sys.argv) == 3:
        return ssh_combine(sys.argv[1], sys.argv[2], 'defaultpass')
    print "error parameter!"

if __name__ == '__main__':
    Main()
