#!/usr/bin/python
import os, sys

default_ip = ['192.168.3.', '192.168.', '192.']

def ssh_connect(user, host):
    param ="-X"
    cmd = "ssh " + param + " " + user + "@" + host
    os.system(cmd)
    pass

def ssh_combine(user, part_ip):
    num = part_ip.count('.')
    if num < 3:
        return ssh_connect(user, default_ip[num] + part_ip)
    else:
        return ssh_connect(user, part_ip)

def Main():
    if len(sys.argv) == 2:
        return ssh_combine('root', sys.argv[1])
    if len(sys.argv) == 3:
        return ssh_combine(sys.argv[1], sys.argv[2])
    print "error parameter!"

if __name__ == '__main__':
    Main()
